import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Header
    dashboard: 'Dashboard',
    options: 'Options',
    optionChain: 'Option Chain',
    sectors: 'Sectors',
    // Dashboard
    tradingSignals: 'Trading Signals',
    add: 'Add',
    stock: 'Stock',
    index: 'Index',
    search: 'Search...',
    all: 'All',
    buy: 'Buy',
    sell: 'Sell',
    hold: 'Hold',
    refresh: 'Refresh',
    refreshing: 'Refreshing...',
    exportCSV: 'Export CSV',
    csv: 'CSV',
    delete: 'Delete',
    cancel: 'Cancel',
    symbol: 'Symbol',
    price: 'Price',
    signal: 'Signal',
    volume: 'Volume (K)',
    week52High: '52W High',
    week52Low: '52W Low',
    yestHigh: 'Yest High',
    yestLow: 'Yest Low',
    time: 'Time',
    action: 'Action',
    addSymbol: 'Add',
    enterSymbol: 'Enter symbol',
    deleteConfirm: 'Are you sure you want to delete',
    addedSuccess: 'added successfully!',
    deletedSuccess: 'deleted successfully!',
    dataRefreshed: 'Data refreshed!',
    refreshFailed: 'Refresh failed',
    symbolRequired: 'Symbol is required',
    // Options
    optionsData: 'Options Data',
    optionsTitle: 'Options',
    addOption: 'Add Option',
    optionSymbol: 'Option Symbol',
    indexOptions: 'Index Options',
    stockOptions: 'Stock Options',
    lotSize: 'Lot Size',
    ltp: 'LTP',
    open: 'Open',
    high: 'High',
    low: 'Low',
    // Option Chain
    optionChainTitle: 'Option Chain',
    strikes: 'Strikes',
    allStrikes: 'All Strikes',
    calls: 'CALLS (CE)',
    puts: 'PUTS (PE)',
    call: 'CALL (CE)',
    put: 'PUT (PE)',
    strike: 'STRIKE',
    openInterest: 'Open Interest',
    change: 'Change',
    oi: 'OI',
    atm: 'ATM',
    noData: 'No option chain data found for',
    // Common
    indices: 'Indices',
    watchlist: 'Watchlist',
    nifty50: 'Nifty 50',
    next50: 'Next 50',
    commodities: 'Commodities',
    crypto: 'Crypto',
    news: 'News',
    noNews: 'No news found for watchlist stocks',
    equityTool: 'Equity Tool',
    charts: 'Charts',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    options: 'ऑप्शन',
    optionChain: 'ऑप्शन चेन',
    sectors: 'सेक्टर',
    tradingSignals: 'ट्रेडिंग सिग्नल',
    add: 'जोड़ें',
    stock: 'स्टॉक',
    index: 'इंडेक्स',
    search: 'खोजें...',
    all: 'सभी',
    buy: 'खरीदें',
    sell: 'बेचें',
    hold: 'होल्ड',
    refresh: 'रिफ्रेश',
    refreshing: 'रिफ्रेश हो रहा...',
    exportCSV: 'CSV डाउनलोड',
    csv: 'CSV',
    delete: 'हटाएं',
    cancel: 'रद्द करें',
    symbol: 'सिंबल',
    price: 'कीमत',
    signal: 'सिग्नल',
    volume: 'वॉल्यूम (K)',
    week52High: '52W उच्च',
    week52Low: '52W निम्न',
    yestHigh: 'कल उच्च',
    yestLow: 'कल निम्न',
    time: 'समय',
    action: 'कार्रवाई',
    addSymbol: 'जोड़ें',
    enterSymbol: 'सिंबल दर्ज करें',
    deleteConfirm: 'क्या आप इसे हटाना चाहते हैं',
    addedSuccess: 'सफलतापूर्वक जोड़ा गया!',
    deletedSuccess: 'सफलतापूर्वक हटाया गया!',
    dataRefreshed: 'डेटा रिफ्रेश हुआ!',
    refreshFailed: 'रिफ्रेश विफल',
    symbolRequired: 'सिंबल आवश्यक है',
    optionsData: 'ऑप्शन डेटा',
    optionsTitle: 'ऑप्शन',
    addOption: 'ऑप्शन जोड़ें',
    optionSymbol: 'ऑप्शन सिंबल',
    indexOptions: 'इंडेक्स ऑप्शन',
    stockOptions: 'स्टॉक ऑप्शन',
    lotSize: 'लॉट साइज़',
    ltp: 'LTP',
    open: 'ओपन',
    high: 'हाई',
    low: 'लो',
    optionChainTitle: 'ऑप्शन चेन',
    strikes: 'स्ट्राइक',
    allStrikes: 'सभी स्ट्राइक',
    calls: 'कॉल (CE)',
    puts: 'पुट (PE)',
    call: 'कॉल (CE)',
    put: 'पुट (PE)',
    strike: 'स्ट्राइक',
    openInterest: 'ओपन इंटरेस्ट',
    change: 'बदलाव',
    oi: 'OI',
    atm: 'ATM',
    noData: 'कोई डेटा नहीं मिला',
    indices: 'इंडेक्स',
    watchlist: 'वॉचलिस्ट',
    nifty50: 'निफ्टी 50',
    next50: 'नेक्स्ट 50',
    commodities: 'कमोडिटी',
    crypto: 'क्रिप्टो',
    news: 'समाचार',
    noNews: 'वॉचलिस्ट स्टॉक के लिए कोई समाचार नहीं मिला',
    equityTool: 'इक्विटी टूल',
    charts: 'चार्ट',
  },
  gu: {
    dashboard: 'ડેશબોર્ડ',
    options: 'ઓપ્શન',
    optionChain: 'ઓપ્શન ચેન',
    sectors: 'સેક્ટર',
    tradingSignals: 'ટ્રેડિંગ સિગ્નલ',
    add: 'ઉમેરો',
    stock: 'સ્ટોક',
    index: 'ઇન્ડેક્સ',
    search: 'શોધો...',
    all: 'બધા',
    buy: 'ખરીદો',
    sell: 'વેચો',
    hold: 'હોલ્ડ',
    refresh: 'રિફ્રેશ',
    refreshing: 'રિફ્રેશ થઈ રહ્યું...',
    exportCSV: 'CSV ડાઉનલોડ',
    csv: 'CSV',
    delete: 'કાઢો',
    cancel: 'રદ કરો',
    symbol: 'સિમ્બોલ',
    price: 'કિંમત',
    signal: 'સિગ્નલ',
    volume: 'વોલ્યુમ (K)',
    week52High: '52W ઉચ્ચ',
    week52Low: '52W નીચું',
    yestHigh: 'ગઈકાલ ઉચ્ચ',
    yestLow: 'ગઈકાલ નીચું',
    time: 'સમય',
    action: 'ક્રિયા',
    addSymbol: 'ઉમેરો',
    enterSymbol: 'સિમ્બોલ દાખલ કરો',
    deleteConfirm: 'શું તમે ખરેખર કાઢવા માંગો છો',
    addedSuccess: 'સફળતાપૂર્વક ઉમેરાયું!',
    deletedSuccess: 'સફળતાપૂર્વક કાઢ્યું!',
    dataRefreshed: 'ડેટા રિફ્રેશ થયો!',
    refreshFailed: 'રિફ્રેશ નિષ્ફળ',
    symbolRequired: 'સિમ્બોલ જરૂરી છે',
    optionsData: 'ઓપ્શન ડેટા',
    optionsTitle: 'ઓપ્શન',
    addOption: 'ઓપ્શન ઉમેરો',
    optionSymbol: 'ઓપ્શન સિમ્બોલ',
    indexOptions: 'ઇન્ડેક્સ ઓપ્શન',
    stockOptions: 'સ્ટોક ઓપ્શન',
    lotSize: 'લોટ સાઇઝ',
    ltp: 'LTP',
    open: 'ઓપન',
    high: 'હાઈ',
    low: 'લો',
    optionChainTitle: 'ઓપ્શન ચેન',
    strikes: 'સ્ટ્રાઇક',
    allStrikes: 'બધા સ્ટ્રાઇક',
    calls: 'કોલ (CE)',
    puts: 'પુટ (PE)',
    call: 'કોલ (CE)',
    put: 'પુટ (PE)',
    strike: 'સ્ટ્રાઇક',
    openInterest: 'ઓપન ઇન્ટરેસ્ટ',
    change: 'ફેરફાર',
    oi: 'OI',
    atm: 'ATM',
    noData: 'કોઈ ડેટા મળ્યો નથી',
    indices: 'ઇન્ડેક્સ',
    watchlist: 'વોચલિસ્ટ',
    nifty50: 'નિફ્ટી 50',
    next50: 'નેક્સ્ટ 50',
    commodities: 'કોમોડિટી',
    crypto: 'ક્રિપ્ટો',
    news: 'સમાચાર',
    noNews: 'વોચલિસ્ટ સ્ટોક માટે કોઈ સમાચાર મળ્યો નથી',
    equityTool: 'ઇક્વિટી ટૂલ',
    charts: 'ચાર્ટ',
  }
};

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en');

  useEffect(() => {
    localStorage.setItem('lang', lang);
  }, [lang]);

  const t = (key) => translations[lang]?.[key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
